### ISSUE TITLE
Missing a way of getting instance to BlogReverseRouter

### ISSUE THREAD

**Issue by v6ak** [jroper/erqx#1]
Hello,
I'd like to write redirects from legacy paths to ERQX paths. I'd like to use BlogReverseRouter, but I can't get an instance of it. The best way I've found is to instantiate a new BlogReverseRouter with correct parameters, but that's somehow suboptimal.

**Comment by jroper** [comment]
This is implemented in 488f8ce, basically, you just need to get a reference to BlogsRouter, and then use the new `reverseRouterFor` with the name of the router to get it.
